---
layout: null
---
{% assign sorted = site.pages | where: "index","primary" | where: "layout","single-bio" %}
{% assign sorted2 = site.pages | where: "index","secondary" | where: "layout","single-bio" %}
var tipuesearch = {"pages": [
  {% for page in sorted %}
     {% assign split0 = page.content | strip_html | strip_newlines | remove: "\" | split: 'Bibliography' %}{% assign split1 = split0[0] | split: 'Bibliografia' %}{% assign split2 = split1[0] | split: 'Bibliographie' %}{% assign split3 = split2[0] | split: 'Notes' %}{% assign split4 = split3[0] | split: 'Fontes' %}{% assign split5 = split4[0] | split: 'Sources' %}{% assign text = split5[0] %}
     {"title" : "{{ page.title | escape }}","text": "{{ text }}", "tags": "{% if page.date != empty %}{{ page.date | join: ' ' }}, {% endif %}{% if page.century != empty %}{{ page.century | join: '-' }} century, {% endif %}{% if page.tradition != empty %}{{ page.tradition | join: ' ' }}, {% endif %}{% if page.affiliation != empty %}{{ page.affiliation | join: ' ' }}, {% endif %}{% if page.country != empty %}{{ page.country | join: ' ' }}, {% endif %}{% if page.ancient == 'ancient' %}{{ page.ancient | join: ' ' }}, {% endif %}{% if page.artist == 'artist' %}{{ page.artist | join: ' ' }}, {% endif %}{% if page.catechist == 'catechist' %}{{ page.catechist | join: ' ' }}, {% endif %}{% if page.clergy == 'clergy' %}{{ page.clergy | join: ' ' }}, {% endif %}{% if page.ecumenists == 'ecumenists' %}{{ page.ecumenists | join: ' ' }}, {% endif %}{% if page.evangelists == 'evangelists' %}{{ page.evangelists | join: ' ' }}, {% endif %}{% if page.nationalists == 'nationalists' %}{{ page.nationalists | join: ' ' }}, {% endif %}{% if page.martyr == 'martyr' %}{{ page.martyr | join: ' ' }}, {% endif %}{% if page.persecuted == 'persecuted' %}{{ page.persecuted | join: ' ' }}, {% endif %}{% if page.medical == 'medical' %}{{ page.medical | join: ' ' }}, {% endif %}{% if page.missionary == 'missionary' %}{{ page.missionary | join: ' ' }}, {% endif %}{% if page.musician == 'musician' %}{{ page.musician | join: ' ' }}, {% endif %}{% if page.nonafrican == 'nonafrican' %}{{ page.nonafrican | join: ' ' }}, {% endif %}{% if page.nonchristian == 'nonchristian' %}{{ page.nonchristian | join: ' ' }}, {% endif %}{% if page.photo == 'photo' %}{{ page.photo | join: ' ' }}, {% endif %}{% if page.scholar == 'scholar' %}{{ page.scholar | join: ' ' }}, {% endif %}{% if page.theologian == 'theologian' %}{{ page.theologian | join: ' ' }}, {% endif %}{% if page.translator == 'translator' %}{{ page.translator | join: ' ' }}, {% endif %}{% if page.women == 'women' %}{{ page.women | join: ' ' }}, {% endif %}{% if page.youth == 'youth' %}{{ page.youth | join: ' ' }}, {% endif %}", "url": "{{ page.permalink }}"},
  {% endfor %}{% for page in sorted %}
    {% assign split0 = page.content | strip_html | strip_newlines | remove: "\" | split: 'Bibliography' %}{% assign split1 = split0[0] | split: 'Bibliografia' %}{% assign split2 = split1[0] | split: 'Bibliographie' %}{% assign split3 = split2[0] | split: 'Notes' %}{% assign split4 = split3[0] | split: 'Fontes' %}{% assign split5 = split4[0] | split: 'Sources' %}{% assign text = split5[0] %}
    {"title" : "{{ page.title | escape }}","text": "{{ text }}", "tags": "{% if page.date != empty %}{{ page.date | join: ' ' }}, {% endif %}{% if page.century != empty %}{{ page.century | join: '-' }} century, {% endif %}{% if page.tradition != empty %}{{ page.tradition | join: ' ' }}, {% endif %}{% if page.affiliation != empty %}{{ page.affiliation | join: ' ' }}, {% endif %}{% if page.country != empty %}{{ page.country | join: ' ' }}, {% endif %}{% if page.ancient == 'ancient' %}{{ page.ancient | join: ' ' }}, {% endif %}{% if page.artist == 'artist' %}{{ page.artist | join: ' ' }}, {% endif %}{% if page.catechist == 'catechist' %}{{ page.catechist | join: ' ' }}, {% endif %}{% if page.clergy == 'clergy' %}{{ page.clergy | join: ' ' }}, {% endif %}{% if page.ecumenists == 'ecumenists' %}{{ page.ecumenists | join: ' ' }}, {% endif %}{% if page.evangelists == 'evangelists' %}{{ page.evangelists | join: ' ' }}, {% endif %}{% if page.nationalists == 'nationalists' %}{{ page.nationalists | join: ' ' }}, {% endif %}{% if page.martyr == 'martyr' %}{{ page.martyr | join: ' ' }}, {% endif %}{% if page.persecuted == 'persecuted' %}{{ page.persecuted | join: ' ' }}, {% endif %}{% if page.medical == 'medical' %}{{ page.medical | join: ' ' }}, {% endif %}{% if page.missionary == 'missionary' %}{{ page.missionary | join: ' ' }}, {% endif %}{% if page.musician == 'musician' %}{{ page.musician | join: ' ' }}, {% endif %}{% if page.nonafrican == 'nonafrican' %}{{ page.nonafrican | join: ' ' }}, {% endif %}{% if page.nonchristian == 'nonchristian' %}{{ page.nonchristian | join: ' ' }}, {% endif %}{% if page.photo == 'photo' %}{{ page.photo | join: ' ' }}, {% endif %}{% if page.scholar == 'scholar' %}{{ page.scholar | join: ' ' }}, {% endif %}{% if page.theologian == 'theologian' %}{{ page.theologian | join: ' ' }}, {% endif %}{% if page.translator == 'translator' %}{{ page.translator | join: ' ' }}, {% endif %}{% if page.women == 'women' %}{{ page.women | join: ' ' }}, {% endif %}{% if page.youth == 'youth' %}{{ page.youth | join: ' ' }}, {% endif %}", "url": "{{ page.permalink }}"}
  {% unless forloop.last %},{% endunless %}
  {% endfor %}
]};
